/*
 * IDENTIFICATION:
 * stub generated Tue Mar 17 02:57:55 2020
 * with a MiG generated by bootstrap_cmds-116
 * OPTIONS: 
 */

/* Module substitute_daemon */

#define	__MIG_check__Request__substitute_daemon_subsystem__ 1

#include "substitute_daemonServer.h"

#ifndef	mig_internal
#define	mig_internal	static __inline__
#endif	/* mig_internal */

#ifndef	mig_external
#define mig_external
#endif	/* mig_external */

#if	!defined(__MigTypeCheck) && defined(TypeCheck)
#define	__MigTypeCheck		TypeCheck	/* Legacy setting */
#endif	/* !defined(__MigTypeCheck) */

#if	!defined(__MigKernelSpecificCode) && defined(_MIG_KERNEL_SPECIFIC_CODE_)
#define	__MigKernelSpecificCode	_MIG_KERNEL_SPECIFIC_CODE_	/* Legacy setting */
#endif	/* !defined(__MigKernelSpecificCode) */

#ifndef	LimitCheck
#define	LimitCheck 0
#endif	/* LimitCheck */

#ifndef	min
#define	min(a,b)  ( ((a) < (b))? (a): (b) )
#endif	/* min */

#if !defined(_WALIGN_)
#define _WALIGN_(x) (((x) + 3) & ~3)
#endif /* !defined(_WALIGN_) */

#if !defined(_WALIGNSZ_)
#define _WALIGNSZ_(x) _WALIGN_(sizeof(x))
#endif /* !defined(_WALIGNSZ_) */

#ifndef	UseStaticTemplates
#define	UseStaticTemplates	0
#endif	/* UseStaticTemplates */

#ifndef MIG_SERVER_ROUTINE
#define MIG_SERVER_ROUTINE
#endif

#ifndef	__DeclareRcvRpc
#define	__DeclareRcvRpc(_NUM_, _NAME_)
#endif	/* __DeclareRcvRpc */

#ifndef	__BeforeRcvRpc
#define	__BeforeRcvRpc(_NUM_, _NAME_)
#endif	/* __BeforeRcvRpc */

#ifndef	__AfterRcvRpc
#define	__AfterRcvRpc(_NUM_, _NAME_)
#endif	/* __AfterRcvRpc */

#ifndef	__DeclareRcvSimple
#define	__DeclareRcvSimple(_NUM_, _NAME_)
#endif	/* __DeclareRcvSimple */

#ifndef	__BeforeRcvSimple
#define	__BeforeRcvSimple(_NUM_, _NAME_)
#endif	/* __BeforeRcvSimple */

#ifndef	__AfterRcvSimple
#define	__AfterRcvSimple(_NUM_, _NAME_)
#endif	/* __AfterRcvSimple */

#define novalue void

#define msgh_request_port	msgh_local_port
#define MACH_MSGH_BITS_REQUEST(bits)	MACH_MSGH_BITS_LOCAL(bits)
#define msgh_reply_port		msgh_remote_port
#define MACH_MSGH_BITS_REPLY(bits)	MACH_MSGH_BITS_REMOTE(bits)

#define MIG_RETURN_ERROR(X, code)	{\
				((mig_reply_error_t *)X)->RetCode = code;\
				((mig_reply_error_t *)X)->NDR = NDR_record;\
				return;\
				}

/* Forward Declarations */


mig_internal novalue _Xsubstitute_setup_process
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP);

mig_internal novalue _Xsubstitute_setup_self
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP);

mig_internal novalue _Xsubstitute_copy_extensions
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP);

mig_internal novalue _Xsubstitute_preflight
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP);


#if ( __MigTypeCheck )
#if __MIG_check__Request__substitute_daemon_subsystem__
#if !defined(__MIG_check__Request__substitute_setup_process_t__defined)
#define __MIG_check__Request__substitute_setup_process_t__defined

mig_internal kern_return_t __MIG_check__Request__substitute_setup_process_t(__attribute__((__unused__)) __Request__substitute_setup_process_t *In0P)
{

	typedef __Request__substitute_setup_process_t __Request;
#if	__MigTypeCheck
	if ((In0P->Head.msgh_bits & MACH_MSGH_BITS_COMPLEX) ||
	    (In0P->Head.msgh_size != (mach_msg_size_t)sizeof(__Request)))
		return MIG_BAD_ARGUMENTS;
#endif	/* __MigTypeCheck */

	return MACH_MSG_SUCCESS;
}
#endif /* !defined(__MIG_check__Request__substitute_setup_process_t__defined) */
#endif /* __MIG_check__Request__substitute_daemon_subsystem__ */
#endif /* ( __MigTypeCheck ) */


/* Routine substitute_setup_process */
mig_internal novalue _Xsubstitute_setup_process
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP)
{

#ifdef  __MigPackStructs
#pragma pack(push, 4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		NDR_record_t NDR;
		pid_t target_pid;
		bool set_exec;
		char set_execPad[3];
		bool should_resume;
		char should_resumePad[3];
		mach_msg_max_trailer_t trailer;
	} Request __attribute__((unused));
#ifdef  __MigPackStructs
#pragma pack(pop)
#endif
	typedef __Request__substitute_setup_process_t __Request;
	typedef __Reply__substitute_setup_process_t Reply __attribute__((unused));

	/*
	 * typedef struct {
	 * 	mach_msg_header_t Head;
	 * 	NDR_record_t NDR;
	 * 	kern_return_t RetCode;
	 * } mig_reply_error_t;
	 */

	Request *In0P = (Request *) InHeadP;
	Reply *OutP = (Reply *) OutHeadP;
	mach_msg_max_trailer_t *TrailerP;
#if	__MigTypeCheck
	unsigned int trailer_size __attribute__((unused));
#endif	/* __MigTypeCheck */
#ifdef	__MIG_check__Request__substitute_setup_process_t__defined
	kern_return_t check_result;
#endif	/* __MIG_check__Request__substitute_setup_process_t__defined */

	__DeclareRcvRpc(31337, "substitute_setup_process")
	__BeforeRcvRpc(31337, "substitute_setup_process")

#if	defined(__MIG_check__Request__substitute_setup_process_t__defined)
	check_result = __MIG_check__Request__substitute_setup_process_t((__Request *)In0P);
	if (check_result != MACH_MSG_SUCCESS)
		{ MIG_RETURN_ERROR(OutP, check_result); }
#endif	/* defined(__MIG_check__Request__substitute_setup_process_t__defined) */

	TrailerP = (mach_msg_max_trailer_t *)((vm_offset_t)In0P +
		round_msg(In0P->Head.msgh_size));
	if (TrailerP->msgh_trailer_type != MACH_MSG_TRAILER_FORMAT_0)
		{ MIG_RETURN_ERROR(In0P, MIG_TRAILER_ERROR); }
#if	__MigTypeCheck
	trailer_size = TrailerP->msgh_trailer_size -
		(mach_msg_size_t)(sizeof(mach_msg_trailer_type_t) - sizeof(mach_msg_trailer_size_t));
#endif	/* __MigTypeCheck */
#if	__MigTypeCheck
	if (trailer_size < (mach_msg_size_t)sizeof(audit_token_t))
		{ MIG_RETURN_ERROR(OutP, MIG_TRAILER_ERROR); }
	trailer_size -= (mach_msg_size_t)sizeof(audit_token_t);
#endif	/* __MigTypeCheck */
	OutP->RetCode = substitute_setup_process(In0P->Head.msgh_request_port, In0P->target_pid, In0P->set_exec, In0P->should_resume, TrailerP->msgh_audit);

	OutP->NDR = NDR_record;


	__AfterRcvRpc(31337, "substitute_setup_process")
}

#if ( __MigTypeCheck )
#if __MIG_check__Request__substitute_daemon_subsystem__
#if !defined(__MIG_check__Request__substitute_setup_self_t__defined)
#define __MIG_check__Request__substitute_setup_self_t__defined

mig_internal kern_return_t __MIG_check__Request__substitute_setup_self_t(__attribute__((__unused__)) __Request__substitute_setup_self_t *In0P)
{

	typedef __Request__substitute_setup_self_t __Request;
#if	__MigTypeCheck
	if ((In0P->Head.msgh_bits & MACH_MSGH_BITS_COMPLEX) ||
	    (In0P->Head.msgh_size != (mach_msg_size_t)sizeof(__Request)))
		return MIG_BAD_ARGUMENTS;
#endif	/* __MigTypeCheck */

	return MACH_MSG_SUCCESS;
}
#endif /* !defined(__MIG_check__Request__substitute_setup_self_t__defined) */
#endif /* __MIG_check__Request__substitute_daemon_subsystem__ */
#endif /* ( __MigTypeCheck ) */


/* Routine substitute_setup_self */
mig_internal novalue _Xsubstitute_setup_self
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP)
{

#ifdef  __MigPackStructs
#pragma pack(push, 4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		mach_msg_max_trailer_t trailer;
	} Request __attribute__((unused));
#ifdef  __MigPackStructs
#pragma pack(pop)
#endif
	typedef __Request__substitute_setup_self_t __Request;
	typedef __Reply__substitute_setup_self_t Reply __attribute__((unused));

	/*
	 * typedef struct {
	 * 	mach_msg_header_t Head;
	 * 	NDR_record_t NDR;
	 * 	kern_return_t RetCode;
	 * } mig_reply_error_t;
	 */

	Request *In0P = (Request *) InHeadP;
	Reply *OutP = (Reply *) OutHeadP;
	mach_msg_max_trailer_t *TrailerP;
#if	__MigTypeCheck
	unsigned int trailer_size __attribute__((unused));
#endif	/* __MigTypeCheck */
#ifdef	__MIG_check__Request__substitute_setup_self_t__defined
	kern_return_t check_result;
#endif	/* __MIG_check__Request__substitute_setup_self_t__defined */

	__DeclareRcvRpc(31338, "substitute_setup_self")
	__BeforeRcvRpc(31338, "substitute_setup_self")

#if	defined(__MIG_check__Request__substitute_setup_self_t__defined)
	check_result = __MIG_check__Request__substitute_setup_self_t((__Request *)In0P);
	if (check_result != MACH_MSG_SUCCESS)
		{ MIG_RETURN_ERROR(OutP, check_result); }
#endif	/* defined(__MIG_check__Request__substitute_setup_self_t__defined) */

	TrailerP = (mach_msg_max_trailer_t *)((vm_offset_t)In0P +
		round_msg(In0P->Head.msgh_size));
	if (TrailerP->msgh_trailer_type != MACH_MSG_TRAILER_FORMAT_0)
		{ MIG_RETURN_ERROR(In0P, MIG_TRAILER_ERROR); }
#if	__MigTypeCheck
	trailer_size = TrailerP->msgh_trailer_size -
		(mach_msg_size_t)(sizeof(mach_msg_trailer_type_t) - sizeof(mach_msg_trailer_size_t));
#endif	/* __MigTypeCheck */
#if	__MigTypeCheck
	if (trailer_size < (mach_msg_size_t)sizeof(audit_token_t))
		{ MIG_RETURN_ERROR(OutP, MIG_TRAILER_ERROR); }
	trailer_size -= (mach_msg_size_t)sizeof(audit_token_t);
#endif	/* __MigTypeCheck */
	OutP->RetCode = substitute_setup_self(In0P->Head.msgh_request_port, TrailerP->msgh_audit);

	OutP->NDR = NDR_record;


	__AfterRcvRpc(31338, "substitute_setup_self")
}

#if ( __MigTypeCheck )
#if __MIG_check__Request__substitute_daemon_subsystem__
#if !defined(__MIG_check__Request__substitute_copy_extensions_t__defined)
#define __MIG_check__Request__substitute_copy_extensions_t__defined

mig_internal kern_return_t __MIG_check__Request__substitute_copy_extensions_t(__attribute__((__unused__)) __Request__substitute_copy_extensions_t *In0P)
{

	typedef __Request__substitute_copy_extensions_t __Request;
#if	__MigTypeCheck
	if (!(In0P->Head.msgh_bits & MACH_MSGH_BITS_COMPLEX) ||
	    (In0P->msgh_body.msgh_descriptor_count != 1) ||
	    (In0P->Head.msgh_size != (mach_msg_size_t)sizeof(__Request)))
		return MIG_BAD_ARGUMENTS;
#endif	/* __MigTypeCheck */

#if	__MigTypeCheck
	if (In0P->task.type != MACH_MSG_PORT_DESCRIPTOR ||
	    In0P->task.disposition != 17)
		return MIG_TYPE_ERROR;
#endif	/* __MigTypeCheck */

	return MACH_MSG_SUCCESS;
}
#endif /* !defined(__MIG_check__Request__substitute_copy_extensions_t__defined) */
#endif /* __MIG_check__Request__substitute_daemon_subsystem__ */
#endif /* ( __MigTypeCheck ) */


/* Routine substitute_copy_extensions */
mig_internal novalue _Xsubstitute_copy_extensions
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP)
{

#ifdef  __MigPackStructs
#pragma pack(push, 4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		/* start of the kernel processed data */
		mach_msg_body_t msgh_body;
		mach_msg_port_descriptor_t task;
		/* end of the kernel processed data */
		mach_msg_max_trailer_t trailer;
	} Request __attribute__((unused));
#ifdef  __MigPackStructs
#pragma pack(pop)
#endif
	typedef __Request__substitute_copy_extensions_t __Request;
	typedef __Reply__substitute_copy_extensions_t Reply __attribute__((unused));

	/*
	 * typedef struct {
	 * 	mach_msg_header_t Head;
	 * 	NDR_record_t NDR;
	 * 	kern_return_t RetCode;
	 * } mig_reply_error_t;
	 */

	Request *In0P = (Request *) InHeadP;
	Reply *OutP = (Reply *) OutHeadP;
	mach_msg_max_trailer_t *TrailerP;
#if	__MigTypeCheck
	unsigned int trailer_size __attribute__((unused));
#endif	/* __MigTypeCheck */
#ifdef	__MIG_check__Request__substitute_copy_extensions_t__defined
	kern_return_t check_result;
#endif	/* __MIG_check__Request__substitute_copy_extensions_t__defined */

	__DeclareRcvRpc(31339, "substitute_copy_extensions")
	__BeforeRcvRpc(31339, "substitute_copy_extensions")

#if	defined(__MIG_check__Request__substitute_copy_extensions_t__defined)
	check_result = __MIG_check__Request__substitute_copy_extensions_t((__Request *)In0P);
	if (check_result != MACH_MSG_SUCCESS)
		{ MIG_RETURN_ERROR(OutP, check_result); }
#endif	/* defined(__MIG_check__Request__substitute_copy_extensions_t__defined) */

	TrailerP = (mach_msg_max_trailer_t *)((vm_offset_t)In0P +
		round_msg(In0P->Head.msgh_size));
	if (TrailerP->msgh_trailer_type != MACH_MSG_TRAILER_FORMAT_0)
		{ MIG_RETURN_ERROR(In0P, MIG_TRAILER_ERROR); }
#if	__MigTypeCheck
	trailer_size = TrailerP->msgh_trailer_size -
		(mach_msg_size_t)(sizeof(mach_msg_trailer_type_t) - sizeof(mach_msg_trailer_size_t));
#endif	/* __MigTypeCheck */
#if	__MigTypeCheck
	if (trailer_size < (mach_msg_size_t)sizeof(audit_token_t))
		{ MIG_RETURN_ERROR(OutP, MIG_TRAILER_ERROR); }
	trailer_size -= (mach_msg_size_t)sizeof(audit_token_t);
#endif	/* __MigTypeCheck */
	OutP->RetCode = substitute_copy_extensions(In0P->Head.msgh_request_port, In0P->task.name, &OutP->stringAddress, &OutP->stringSize, TrailerP->msgh_audit);
	if (OutP->RetCode != KERN_SUCCESS) {
		MIG_RETURN_ERROR(OutP, OutP->RetCode);
	}

	OutP->NDR = NDR_record;


	OutP->Head.msgh_size = (mach_msg_size_t)(sizeof(Reply));
	__AfterRcvRpc(31339, "substitute_copy_extensions")
}

#if ( __MigTypeCheck )
#if __MIG_check__Request__substitute_daemon_subsystem__
#if !defined(__MIG_check__Request__substitute_preflight_t__defined)
#define __MIG_check__Request__substitute_preflight_t__defined

mig_internal kern_return_t __MIG_check__Request__substitute_preflight_t(__attribute__((__unused__)) __Request__substitute_preflight_t *In0P)
{

	typedef __Request__substitute_preflight_t __Request;
#if	__MigTypeCheck
	if (!(In0P->Head.msgh_bits & MACH_MSGH_BITS_COMPLEX) ||
	    (In0P->msgh_body.msgh_descriptor_count != 1) ||
	    (In0P->Head.msgh_size != (mach_msg_size_t)sizeof(__Request)))
		return MIG_BAD_ARGUMENTS;
#endif	/* __MigTypeCheck */

#if	__MigTypeCheck
	if (In0P->task.type != MACH_MSG_PORT_DESCRIPTOR ||
	    In0P->task.disposition != 17)
		return MIG_TYPE_ERROR;
#endif	/* __MigTypeCheck */

	return MACH_MSG_SUCCESS;
}
#endif /* !defined(__MIG_check__Request__substitute_preflight_t__defined) */
#endif /* __MIG_check__Request__substitute_daemon_subsystem__ */
#endif /* ( __MigTypeCheck ) */


/* Routine substitute_preflight */
mig_internal novalue _Xsubstitute_preflight
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP)
{

#ifdef  __MigPackStructs
#pragma pack(push, 4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		/* start of the kernel processed data */
		mach_msg_body_t msgh_body;
		mach_msg_port_descriptor_t task;
		/* end of the kernel processed data */
		NDR_record_t NDR;
		mach_vm_address_t pathAddress;
		mach_vm_size_t pathSize;
		mach_msg_max_trailer_t trailer;
	} Request __attribute__((unused));
#ifdef  __MigPackStructs
#pragma pack(pop)
#endif
	typedef __Request__substitute_preflight_t __Request;
	typedef __Reply__substitute_preflight_t Reply __attribute__((unused));

	/*
	 * typedef struct {
	 * 	mach_msg_header_t Head;
	 * 	NDR_record_t NDR;
	 * 	kern_return_t RetCode;
	 * } mig_reply_error_t;
	 */

	Request *In0P = (Request *) InHeadP;
	Reply *OutP = (Reply *) OutHeadP;
	mach_msg_max_trailer_t *TrailerP;
#if	__MigTypeCheck
	unsigned int trailer_size __attribute__((unused));
#endif	/* __MigTypeCheck */
#ifdef	__MIG_check__Request__substitute_preflight_t__defined
	kern_return_t check_result;
#endif	/* __MIG_check__Request__substitute_preflight_t__defined */

	__DeclareRcvRpc(31340, "substitute_preflight")
	__BeforeRcvRpc(31340, "substitute_preflight")

#if	defined(__MIG_check__Request__substitute_preflight_t__defined)
	check_result = __MIG_check__Request__substitute_preflight_t((__Request *)In0P);
	if (check_result != MACH_MSG_SUCCESS)
		{ MIG_RETURN_ERROR(OutP, check_result); }
#endif	/* defined(__MIG_check__Request__substitute_preflight_t__defined) */

	TrailerP = (mach_msg_max_trailer_t *)((vm_offset_t)In0P +
		round_msg(In0P->Head.msgh_size));
	if (TrailerP->msgh_trailer_type != MACH_MSG_TRAILER_FORMAT_0)
		{ MIG_RETURN_ERROR(In0P, MIG_TRAILER_ERROR); }
#if	__MigTypeCheck
	trailer_size = TrailerP->msgh_trailer_size -
		(mach_msg_size_t)(sizeof(mach_msg_trailer_type_t) - sizeof(mach_msg_trailer_size_t));
#endif	/* __MigTypeCheck */
#if	__MigTypeCheck
	if (trailer_size < (mach_msg_size_t)sizeof(audit_token_t))
		{ MIG_RETURN_ERROR(OutP, MIG_TRAILER_ERROR); }
	trailer_size -= (mach_msg_size_t)sizeof(audit_token_t);
#endif	/* __MigTypeCheck */
	OutP->RetCode = substitute_preflight(In0P->Head.msgh_request_port, In0P->task.name, In0P->pathAddress, In0P->pathSize, TrailerP->msgh_audit);

	OutP->NDR = NDR_record;


	__AfterRcvRpc(31340, "substitute_preflight")
}



/* Description of this subsystem, for use in direct RPC */
const struct substitute_daemon_subsystem substitute_daemon_subsystem = {
	substitute_daemon_server_routine,
	31337,
	31341,
	(mach_msg_size_t)sizeof(union __ReplyUnion__substitute_daemon_subsystem),
	(vm_address_t)0,
	{
          { (mig_impl_routine_t) 0,
          (mig_stub_routine_t) _Xsubstitute_setup_process, 12, 0, (routine_arg_descriptor_t)0, (mach_msg_size_t)sizeof(__Reply__substitute_setup_process_t)},
          { (mig_impl_routine_t) 0,
          (mig_stub_routine_t) _Xsubstitute_setup_self, 9, 0, (routine_arg_descriptor_t)0, (mach_msg_size_t)sizeof(__Reply__substitute_setup_self_t)},
          { (mig_impl_routine_t) 0,
          (mig_stub_routine_t) _Xsubstitute_copy_extensions, 12, 0, (routine_arg_descriptor_t)0, (mach_msg_size_t)sizeof(__Reply__substitute_copy_extensions_t)},
          { (mig_impl_routine_t) 0,
          (mig_stub_routine_t) _Xsubstitute_preflight, 14, 0, (routine_arg_descriptor_t)0, (mach_msg_size_t)sizeof(__Reply__substitute_preflight_t)},
	}
};

mig_external boolean_t substitute_daemon_server
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP)
{
	/*
	 * typedef struct {
	 * 	mach_msg_header_t Head;
	 * 	NDR_record_t NDR;
	 * 	kern_return_t RetCode;
	 * } mig_reply_error_t;
	 */

	mig_routine_t routine;

	OutHeadP->msgh_bits = MACH_MSGH_BITS(MACH_MSGH_BITS_REPLY(InHeadP->msgh_bits), 0);
	OutHeadP->msgh_remote_port = InHeadP->msgh_reply_port;
	/* Minimal size: routine() will update it if different */
	OutHeadP->msgh_size = (mach_msg_size_t)sizeof(mig_reply_error_t);
	OutHeadP->msgh_local_port = MACH_PORT_NULL;
	OutHeadP->msgh_id = InHeadP->msgh_id + 100;
	OutHeadP->msgh_reserved = 0;

	if ((InHeadP->msgh_id > 31340) || (InHeadP->msgh_id < 31337) ||
	    ((routine = substitute_daemon_subsystem.routine[InHeadP->msgh_id - 31337].stub_routine) == 0)) {
		((mig_reply_error_t *)OutHeadP)->NDR = NDR_record;
		((mig_reply_error_t *)OutHeadP)->RetCode = MIG_BAD_ID;
		return FALSE;
	}
	(*routine) (InHeadP, OutHeadP);
	return TRUE;
}

mig_external mig_routine_t substitute_daemon_server_routine
	(mach_msg_header_t *InHeadP)
{
	int msgh_id;

	msgh_id = InHeadP->msgh_id - 31337;

	if ((msgh_id > 3) || (msgh_id < 0))
		return 0;

	return substitute_daemon_subsystem.routine[msgh_id].stub_routine;
}
